controller_list:
  - name: arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  - name: robotiq_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
    - robotiq_85_left_knuckle_joint

initial:  # Define initial robot poses per group
  - group: irb_120
    pose: home
  - group: robotiq_gripper
    pose: open_gripper
